theme: jekyll-theme-slate

title: 'DiP: Diverse Generation Precondition'

tagline: Precondition | Generation | Diverse | Precondition Generation | Diverse Generation | Event

plugins:
  - jekyll-seo-tag
